# Numpy

In [2]:
#importar el modulo
import numpy as np

In [2]:
L1 = [1,2,3,4,5,6,7,8]  #Crear una lista

In [3]:
#numpy convierte a array las listas

In [4]:
x1 = np.array(L1)
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
x2 = np.array(L1, dtype='float32') #admite numero con coma
x2

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

In [9]:
#Tipos de datos para dtype
- bool_
- int_, intc, intp, int8, int16, int32, int64
- uint8,uint16,uint32,uint64  #Entero sin signo
- float_, float16,float32,float64
- complex_, complex64,complex128 #(a+bi, a,b  E float_)

NameError: name 'bool_' is not defined

In [10]:
np.zeros((3,4)) # Iniciar array o matiz de 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.arange(10) # hace un array de 10 numeros

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(3,12, dtype=np.float)

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [17]:
np.arange(4,5,0.1) # de 0.1 en 0.1

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [20]:
np.linspace(1.,7., 12) # pone 12 numeros en medio de 1 y 7

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [21]:
np.eye(5) # Arma un matriz de 5 filas y 5 columnas

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
x= np.zeros((8,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
x.reshape((6,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
x.reshape((3,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
x = np.array([[1,2,3,4],[5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [33]:
np.ravel(x) #aplanar la matiz - se usa en Machine Learning

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
x.flatten() #copia el array y lo aplana.(se hace en una copia)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
np.transpose(x) #intercambia filas y columnas

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [37]:
np.resize(x, (5,3)) # Arma la matriz de la manera que los armemos, si le faltan datos copia al final

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

1. Crear un array con valores entre 5 y 120
2. Crear una matriz 4 x4 con valores de 0 a 15
3. Crear la identidad 7x7
4. crear un array de 20 elementos y transformarlo en un matriz 5x4
5. Crear un array con 20 numeros con los valores en tre 0 y 5 espaciado de forma uniforme

In [83]:
#1.
np.arange(5,120)

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108,
       109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119])

In [95]:
x = np.zeros((7,7))
x

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [92]:
j=np.arange(20)
j.resize((5,4))
j

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [101]:
np.linspace(0.,5., 20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

# Propiedades de los array

In [38]:
x = np.arange(12)
x = x.reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
x.ndim # dimensiones

2

In [41]:
x.shape # cada una de las dimensiones

(3, 4)

In [43]:
x.size # cantidad de elemtos en la matrix

12

In [44]:
x.dtype # tipo de dato de la matriz

dtype('int32')

In [45]:
x.itemsize # Tamaño/peso de cada uno de los elementos de la matriz

4

In [47]:
x.data # donde se almacena en la memoria Ram

In [52]:
x[2,1]

9

In [54]:
x.shape = (4,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
x[1:3, 0:2] #trae las filas 1:3 u columnas de la 0:2

array([[3, 4],
       [6, 7]])

In [57]:
y= np.arange(12)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [58]:
y[3:8]  #Muestra del 3 al 8

array([3, 4, 5, 6, 7])

In [59]:
y[1:7:2] #del 1 al 7 de 2 en 2

array([1, 3, 5])

In [63]:
z = np.arange(10,6,-1)
z

array([10,  9,  8,  7])

In [66]:
y[z]

array([10,  9,  8,  7])

In [68]:
x = np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [69]:
x[x>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [72]:
cond = x < 25
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [73]:
x[cond]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [74]:
x[12:24] = 1 # del 12 al 24 pone 1
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [76]:
x[13:16] = [6,9,12]
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [78]:
x.dtype

dtype('int32')

In [81]:
x[5] = 3.1415
x

array([ 0,  1,  2,  3,  4,  3,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
x[8]

# Copias y vistas de Array

In [3]:
x = np.arange(10)

In [5]:
y = x #referencia de x no lo cambia

In [7]:
y.shape = (2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
z = x.copy()
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [12]:
z is x

False

In [13]:
y is x

True

In [14]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
t = x.view() # vista de X
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
t.shape =(5,2)
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [19]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
s = x [0:2, 1:3] # Esto es una lista
s

array([[1, 2],
       [6, 7]])

In [22]:
s[:] =5 #Cambia todos los elementos a 5
s

array([[5, 5],
       [5, 5]])

# FUNCIONES UNIVERSALES (ufunc)
- Unarias : sqrt, sin,cos, **2
- Binarias: maximum, minimum

In [23]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x+3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [26]:
alpha = np.linspace(0,2*np.pi,4)
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [27]:
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [29]:
np.cos(alpha)

array([ 1. , -0.5, -0.5,  1. ])

In [30]:
np.tan(alpha)

array([ 0.00000000e+00, -1.73205081e+00,  1.73205081e+00, -2.44929360e-16])

In [31]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.power(3,x) # 3 elevado a x

In [35]:
np.power(x,2) # el array a las 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

$$\sum_{i=1}^n x_i$$

In [33]:
np.sum(x) #suma toda el array

45

In [34]:
np.nansum(x) # suma todo menos los NaN

45

In [36]:
np.prod(x)

0

In [37]:
np.mean(x)

4.5

In [38]:
np.min(x)

0

In [39]:
np.argmin(x) #muestra la posicion donde esta el valor minimo

0

In [40]:
np.argmax(x) # muestra la posicion donde esta el valor mas alto

9

In [46]:
np.percentile(x, q=0.95) # nose

0.08549999999999999

In [61]:
y = np.array([True,True,True])

In [62]:
np.any(y) #muestra si hay un 0 o no

True

In [63]:
np.all(y) #devuelve si todos son true o false

True

In [65]:
# se peude usar random.seed(2019) y lo que hace 
#es fijar los numeros random y ponerle de nombre 2019
z = np.random.random((3,5))
z

array([[0.60029596, 0.11881846, 0.88297238, 0.721747  , 0.51350132],
       [0.2856267 , 0.98640104, 0.37107905, 0.53511942, 0.44226766],
       [0.29490745, 0.80836188, 0.04753609, 0.83982669, 0.15255429]])

In [68]:
z.sum()

7.6010154023674525

In [69]:
z.sum(axis=0) #suma por columnas

array([1.18083011, 1.91358138, 1.30158753, 2.09669311, 1.10832327])

In [70]:
z.sum(axis=1) #suma las filas

array([2.83733513, 2.62049387, 2.1431864 ])

In [ ]:
np.random.seed

In [ ]:
np.su