# Tema 1
vamos a ver como crear una matriz utulizando lla libreria `numpy`

In [2]:
row = [1,2,3]
row

[1, 2, 3]

In [3]:
col = [[1],[2],[3]]

In [4]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
matriz[1][1]

5

In [6]:
matriz [0][0]

1

In [26]:
matriz[0]

[1, 2, 3]

In [27]:
for row in matriz:
    print(row[0])

1
4
7


In [8]:
2*matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
import numpy as np

In [11]:
matriz2 = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype= complex #complex/real) #aca ya usamos numpy
matriz2

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.shape(matriz2)

(3, 3)

In [17]:
A = np.array([[1,2],[3,4]])
B = np.array([[3,0],[1,-1]])
A+B

array([[4, 2],
       [4, 3]])

In [19]:
print(A.dot(B)) #con print saca el cartel array

[[ 5 -2]
 [13 -4]]


In [22]:
print(A.transpose)

<built-in method transpose of numpy.ndarray object at 0x000001A3B9559DF0>


In [25]:
np.linalg.matrix_rank(A)

2

NO se hace la inversa de una matriz cuadrada , ni de una matriz cuyo rango sea inferior a su 
orden(el numero de filas / columnas de la misma)