In [69]:
import pandas as pd
import numpy as np
import math

In [150]:
df=pd.read_table('./dataframe/datacrab.txt', delimiter=' ')

In [151]:
cw=df.width

In [152]:
n = len(cw)

# Regla de Scott

In [153]:
As= 3.5*cw.std()*n**(-1/3) #amplitud teorica
k= math.ceil((cw.max()-cw.min())/(As))


In [154]:
A1 = (cw.max()-cw.min())/k


In [155]:
A=1.3 #aca lo aproximamos al valor que mejor cuadre para el hist

# Calcular los Extremos

In [156]:
L1 = cw.min()-1/2*0.1

# Rango

In [157]:
L = L1 + A*np.arange(11)

# Marcas de clase

In [158]:
X1 = (L[0]+L[1])/2

In [160]:
X2 = X1 + A*np.arange(10)
X2

array([21.6, 22.9, 24.2, 25.5, 26.8, 28.1, 29.4, 30.7, 32. , 33.3])

# Regla de la Raiz en Python

In [133]:
k1 = math.ceil(math.sqrt(n))# tomo la parte entera de la raiz cuadrada de n hacia arriba
print(k1)

14


In [134]:
A= (cw.max()-cw.min())/k1 #Amplitud del rango
A

0.8928571428571429

In [135]:
L2=cw.min()-1/2*0.14#Calcular los extremos de los intervalos
print(L2)

20.93


In [143]:
L3=L2+A*np.arange(11) #Marcas de Intervalo
L3=np.round(L3,2)
L3

array([20.93, 21.82, 22.72, 23.61, 24.5 , 25.39, 26.29, 27.18, 28.07,
       28.97, 29.86])

In [145]:
X1=(L[0]+L[1])/2#Marca de clase
X1
X = X1+A*np.arange(10)
X

array([21.6       , 22.49285714, 23.38571429, 24.27857143, 25.17142857,
       26.06428571, 26.95714286, 27.85      , 28.74285714, 29.63571429])

# Regla de Sturges

In [161]:
k2 = math.ceil(1+math.log(n,2)) # tomo la parte entera hacia arriba 
print(k2)

9


In [162]:
A = (cw.max()-cw.min())/k2 #Amplitud de los intevalos
A

1.3888888888888888

In [163]:
L1 = cw.min()-1/2*0.09#extremo delos intevalos
L1

20.955

In [168]:
L = L1+A*np.arange(11)
L

array([20.955     , 22.34388889, 23.73277778, 25.12166667, 26.51055556,
       27.89944444, 29.28833333, 30.67722222, 32.06611111, 33.455     ,
       34.84388889])

In [174]:
X1=(L[0]+L[1])/2#Marcas de la clase
X1
X = np.round(X1+A*np.arange(10),2)
X

array([21.65, 23.04, 24.43, 25.82, 27.2 , 28.59, 29.98, 31.37, 32.76,
       34.15])

# Regla Freedman-Diaconis


In [175]:
afd= 2*(cw.quantile(0.75)-cw.quantile(0.25))*n**(-1/3)#Amplitud teórica
k3=math.ceil((cw.max()-cw.min())/afd)
print(k3)

13


In [176]:
A= (cw.max()-cw.min())/k3 #Amplitud de los intervalos
A

0.9615384615384616

In [178]:
L1=cw.min()-1/2*(k3/100) #Extremos de los intevalos
L1

20.935

In [179]:
L =L1+A*np.arange(11)
L

array([20.935     , 21.89653846, 22.85807692, 23.81961538, 24.78115385,
       25.74269231, 26.70423077, 27.66576923, 28.62730769, 29.58884615,
       30.55038462])

In [181]:
X1=(L[0]+L[1])/2 #Calcular marca de la clase
X1

21.41576923076923

In [182]:
X= X1+A*np.arange(10)
X = np.round(X,2)
print(X)

[21.42 22.38 23.34 24.3  25.26 26.22 27.18 28.15 29.11 30.07]
